local Messages = {
	ERROR = {
		SA_INV_NAME = 'Invalid name, string expected, got "%s"',
		SA_INV_IMGLB = 'Invalid ImageLabel, ImageLabel expected, got "%s"',
		SA_INV_GRIDSIZE = 'Invalid gridSize, number expected, got "%s"',
		SA_INV_FRATE = 'Invalid framerate, number expected, got "%s"',
		
		SA_INV_IMGSIZE = 'Invalid imageSize, number expected, got "%s"',
		
		SA_INV_EDIT_T = 'Invalid table, table expected, got "%s"',
		SA_INV_EDIT = 'Invalid %s, %s expected, got "%s"',
		SA_INV_EDIT_V = 'Invalid value, /n valid values : "github doc link"' --TODO
	},
	
	WARN = {

	},
	
	INFO = {

	}
	
	
}

return Messages
